name: integration-test

on:
  - push

jobs:

  test:
    name: test
    runs-on: ubuntu-20.04
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: build-image
        run: |
          export DFINITY_REV=$(curl -H "Authorization: token ${{ github.token }}" -L https://api.github.com/repos/dfinity-lab/dfinity/branches/master | jq -r .commit.sha)
          echo "dfinity-lab/dfinity rev: $DFINITY_REV"

          pushd $(mktemp -d)

          curl -H "Authorization: token ${{ github.token }}" -L https://api.github.com/repos/dfinity-lab/dfinity/tarball/$DFINITY_REV | tar xz --strip-components=1

          pushd rs/rosetta-api/docker

          podman build \
            --file local-deployment.Dockerfile \
            --build-arg GITHUB_TOKEN=${{ github.token }} \
            --build-arg RELEASE=$DFINITY_REV \
            --pull \
            --tag dfinity \
            .

          popd

          popd
