name: pack

on:
  - push
  - pull_request

jobs:

  pack:
    name: pack
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: pack
        run: |
          npm pack
          pushd $(mktemp -d)
          npm install $GITHUB_WORKSPACE/*.tgz
          node --eval 'console.log(require("@dfinity/rosetta-client"))'
          popd
