name: protobuf-check

on:
  push:
  pull_request:
  schedule:
    - cron: "0 * * * *"

jobs:

  protobuf-check:
    name: protobuf-check
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: checkout-dfinity
        uses: actions/checkout@v2
        with:
          repository: dfinity-lab/dfinity
          token: ${{ secrets.GH_TOKEN }}
          path: dfinity

      - name: setup-nix
        uses: cachix/install-nix-action@v13

      - name: setup-protoc
        run: |
          nix-channel --add https://nixos.org/channels/nixpkgs-unstable
          nix-channel --update
          nix-env -iA nixpkgs.protobuf3_13

      - name: check
        run: |
          pushd dfinity/rs/rosetta-api/ledger_canister

          protoc \
            --js_out \
            import_style=commonjs,binary:${{ github.workspace }}/autogen \
            --proto_path proto \
            --proto_path ../../types/base_types/proto \
            proto/ic_ledger/pb/v1/types.proto \
            ../../types/base_types/proto/ic_base_types/pb/v1/types.proto

          popd

          git diff --exit-code
