name: protobuf-check

on:
  push:
  pull_request:
  schedule:
    - cron: "0 * * * *"

jobs:

  protobuf-check:
    name: protobuf-check
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: checkout-ic
        run: |
          pushd ${{ runner.temp }}
          curl -L https://github.com/dfinity/ic/archive/refs/heads/master.tar.gz | tar xz
          mv ic-master ic
          popd

      - name: setup-protoc
        run: |
          mkdir ~/.local
          pushd ${{ runner.temp }}
          curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.18.1/protoc-3.18.1-linux-x86_64.zip -O
          unzip protoc-3.18.1-linux-x86_64.zip -d ~/.local
          popd
          echo ~/.local/bin >> $GITHUB_PATH

      - name: check
        run: |
          pushd ${{ runner.temp }}/ic/rs/rosetta-api/ledger_canister

          protoc \
            --js_out \
            import_style=commonjs,binary:${{ github.workspace }}/autogen \
            --proto_path proto \
            --proto_path ../../types/base_types/proto \
            proto/ic_ledger/pb/v1/types.proto \
            ../../types/base_types/proto/ic_base_types/pb/v1/types.proto

          popd

          git diff --exit-code
